name: "Alexa Shopping List Scraper"
description: "The project scrapes the Amazon Shopping List page and add the items to the Home Assistant Shopping List (todo list) every 3 minutes"
version: "1.1.3"
slug: "alexa_shopping_list_scraper"
init: false
url: "https://github.com/Infraviored/alexa_list_ha_import"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
options:
  HA_Webhook_URL: "HOME_ASSISTANT_WEBHOOK_URL"
  Amazon_Shopping_List_Page: "https://www.amazon.com/alexaquantum/sp/alexaShoppingList?ref_=list_d_wl_ys_list_1"
  Pooling_Interval: "180"
  Delete_After_Download: False
  Debug_Log: False
  Cookies_JSON: ""
schema:
  HA_Webhook_URL: str
  Amazon_Shopping_List_Page: str
  Pooling_Interval: int
  Delete_After_Download: bool
  Debug_Log: bool 
  Cookies_JSON: str
ports:
  8888/tcp: 8888
ports_description:
  8888/tcp: Web interface for DEBUG ONLY
